# Generated by Django 3.0.7 on 2020-08-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='margin',
            field=models.FloatField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='addressl2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='enddate',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='startdate',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='addressl2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
