# Generated by Django 3.0.7 on 2020-08-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200804_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
