# Generated by Django 3.0.7 on 2020-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200804_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
